Repository DO-SOPT-APP3-Airbnb/Airbnb-iOS, pull requests merged in 2023-11, with the labels that each got.

#5 Feat [#4] 커스텀 네비게이션 바 구현
  Airbnb-iOS.xcodeproj/project.pbxproj
  Airbnb-iOS/Resource/Assets.xcassets/btn_x.imageset/Contents.json
  Airbnb-iOS/Resource/Assets.xcassets/btn_x.imageset/btn_x.png
  Airbnb-iOS/Resource/Assets.xcassets/btn_x.imageset/btn_x@2x.png
  Airbnb-iOS/Resource/Assets.xcassets/btn_x.imageset/btn_x@3x.png
  Airbnb-iOS/Resource/Literals/ImageLiteral.swift
  Airbnb-iOS/Source/Extension/UILabel+.swift
  Airbnb-iOS/Source/Extension/UIStackView+.swift
  Airbnb-iOS/Source/Extension/UIView+.swift
  Airbnb-iOS/Source/Scenes/Helper/CustomNavigationView.swift
Labels: 🌟 Feature, 🐰 지희

#8 Feat [#1] WhereView 상단 UI 구현
  Airbnb-iOS.xcodeproj/project.pbxproj
  Airbnb-iOS/Resource/Assets.xcassets/img_whare.imageset/Contents.json
  Airbnb-iOS/Resource/Assets.xcassets/img_whare.imageset/img_whare.png
  Airbnb-iOS/Resource/Assets.xcassets/img_whare.imageset/img_whare@2x.png
  Airbnb-iOS/Resource/Assets.xcassets/img_whare.imageset/img_whare@3x.png
  Airbnb-iOS/Resource/Literals/ImageLiteral.swift
  Airbnb-iOS/Source/Scenes/ViewController.swift
  Airbnb-iOS/Source/Scenes/Where/WhereCollectionViewCell.swift
  Airbnb-iOS/Source/Scenes/Where/WhereViewController.swift
Labels: 🌟 Feature, 🐶 효리

#6 Feat [#3] 날짜 선택(WhenView) 구현
  Airbnb-iOS.xcodeproj/project.pbxproj
  Airbnb-iOS/Resource/Assets.xcassets/ic_+-.imageset/Contents.json
  Airbnb-iOS/Resource/Assets.xcassets/ic_+-.imageset/ic_+-.png
  Airbnb-iOS/Resource/Assets.xcassets/ic_+-.imageset/ic_+-@2x.png
  Airbnb-iOS/Resource/Assets.xcassets/ic_+-.imageset/ic_+-@3x.png
  Airbnb-iOS/Resource/Assets.xcassets/img_when.imageset/Contents.json
  Airbnb-iOS/Resource/Assets.xcassets/img_when.imageset/img_when.png
  Airbnb-iOS/Resource/Assets.xcassets/img_when.imageset/img_when@2x.png
  Airbnb-iOS/Resource/Assets.xcassets/img_when.imageset/img_when@3x.png
  Airbnb-iOS/Resource/Literals/ImageLiteral.swift
  Airbnb-iOS/Source/Extension/Adjust+.swift
  Airbnb-iOS/Source/Extension/String+.swift
  Airbnb-iOS/Source/Extension/UIButton+.swift
  Airbnb-iOS/Source/Extension/UIScreen+.swift
  Airbnb-iOS/Source/Scenes/Helper/CustomNavigationView.swift
  Airbnb-iOS/Source/Scenes/WhenScene/CalendarDateFormatter.swift
  Airbnb-iOS/Source/Scenes/WhenScene/Cells/DateSelectCollectionViewCell.swift
  Airbnb-iOS/Source/Scenes/WhenScene/Cells/MonthlyCollectionViewCell.swift
  Airbnb-iOS/Source/Scenes/WhenScene/Helper/CalendarView.swift
  Airbnb-iOS/Source/Scenes/WhenScene/Helper/SegmentButton.swift
  Airbnb-iOS/Source/Scenes/WhenScene/ViewControllers/WhenViewController.swift
  Airbnb-iOS/Source/Scenes/WhenScene/Views/WhenView.swift
Labels: 🌟 Feature, 🐰 지희

#12 Feat [#7] 인원 선택 뷰 구현 완료
  Airbnb-iOS.xcodeproj/project.pbxproj
  Airbnb-iOS/Resource/Assets.xcassets/img_who.imageset/Contents.json
  Airbnb-iOS/Resource/Assets.xcassets/img_who.imageset/img_who.png
  Airbnb-iOS/Resource/Assets.xcassets/img_who.imageset/img_who@2x.png
  Airbnb-iOS/Resource/Literals/ImageLiteral.swift
  Airbnb-iOS/Source/Scenes/WhenScene/CalendarDateFormatter.swift
  Airbnb-iOS/Source/Scenes/WhenScene/Helper/CalendarDateFormatter.swift
  Airbnb-iOS/Source/Scenes/WhenScene/ViewControllers/WhenViewController.swift
  Airbnb-iOS/Source/Scenes/WhoScene/Cells/AccompanyTableViewCell.swift
  Airbnb-iOS/Source/Scenes/WhoScene/ViewControllers/WhoViewViewController.swift
  Airbnb-iOS/Source/Scenes/WhoScene/Views/WhoView.swift
Labels: 🌟 Feature, 🐰 지희

#17 Network [#16] 네트워크 세팅
  Airbnb-iOS.xcodeproj/project.pbxproj
  Airbnb-iOS/Info.plist
  Airbnb-iOS/Source/Services/Config.swift
  Airbnb-iOS/Source/Services/NetworkError.swift
Labels: ⚙ Setting, 🐰 지희

#19 Feat/#11 where scroll view
  Airbnb-iOS.xcodeproj/project.pbxproj
  Airbnb-iOS/Source/Scenes/Where/WhereCollectionViewCell.swift
  Airbnb-iOS/Source/Scenes/Where/WhereViewController.swift
  Airbnb-iOS/Source/Supports/SceneDelegate.swift
Labels: 🌟 Feature, 🐶 효리
